// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: feed_followers.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollower = `-- name: CreateFeedFollower :one
INSERT into feed_followers (id,created_at,updated_at,user_id,feed_id) VALUES ($1, $2, $3, $4, $5) RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateFeedFollowerParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateFeedFollower(ctx context.Context, arg CreateFeedFollowerParams) (FeedFollower, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollower,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FeedFollower
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const getFeedsFollows = `-- name: GetFeedsFollows :many
SELECT id, created_at, updated_at, user_id, feed_id FROM feed_followers WHERE user_id = $1
`

func (q *Queries) GetFeedsFollows(ctx context.Context, userID uuid.UUID) ([]FeedFollower, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsFollows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollower
	for rows.Next() {
		var i FeedFollower
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
